version: '2'
services:
  elasticsearch:
    build: ./elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      cluster.name: "docker-cluster"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      cluster.routing.allocation.disk.watermark.low: "500mb"
      cluster.routing.allocation.disk.watermark.high: "500mb"
      cluster.routing.allocation.disk.watermark.flood_stage: "100mb"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
