
[default]
SCHOLAR_ENV = "default"
SCHOLAR_ISSUEDB_PATH = "data/issue_db.sqlite"
I18N_LANG_DEFAULT = "en"
FATCAT_ELASTICSEARCH_BACKEND = "https://search.fatcat.wiki"
ELASTICSEARCH_BACKEND = "http://search-svc097.fatcat.wiki:9292"
ELASTICSEARCH_FRONTEND = "http://search-svc097.fatcat.wiki:9292"
ELASTICSEARCH_FULLTEXT_INDEX = "scholar_fulltext"
THUMBNAIL_URL_PREFIX = "https://blobs.fatcat.wiki/thumbnail/pdf/"
SANDCRAWLER_DB_API = "http://aitio.us.archive.org:3030"
SANDCRAWLER_S3_API = "wbgrp-svc169.us.archive.org:8333"
KAFKA_BROKERS = []
FATCAT_API_HOST = "https://api.fatcat.wiki/v0"
INDEX_WORKER_BATCH_SIZE = 50
SENTRY_DSN = ""
ENABLE_GOATCOUNTER = false
GOATCOUNTER_ENDPOINT = "https://goatcounter.scholar.fatcat.wiki/count"
GOATCOUNTER_SCRIPT_URL = "https://goatcounter.scholar.fatcat.wiki/count.js"
ONION_DOMAIN = "scholar-qa.archivev3qli37bju4rlh27glh24lljyezwxf4pokmrdbpefjlcrp5id.onion"
ENABLE_PROMETHEUS = false

[test]
SCHOLAR_ENV = "test"
FATCAT_API_HOST = "http://disabled-during-tests-bogus.xyz:3333"
ELASTICSEARCH_FRONTEND = "http://disabled-during-tests-bogus.xyz:3333"
ELASTICSEARCH_BACKEND = "http://disabled-during-tests-bogus.xyz:3333"
SCHOLAR_ISSUEDB_PATH = ":memory:"

[development]
SCHOLAR_ENV = "dev"
ELASTICSEARCH_FULLTEXT_INDEX = "dev_scholar_fulltext"
ELASTICSEARCH_BACKEND = "http://localhost:9200"
ELASTICSEARCH_FRONTEND = "http://localhost:9200"
KAFKA_BROKERS = ["localhost"]
FATCAT_API_HOST = "http://localhost:9411/v0"

[qa]
SCHOLAR_ENV = "qa"
ELASTICSEARCH_FULLTEXT_INDEX = "scholar_fulltext_v01"
KAFKA_BROKERS = ["wbgrp-svc263.us.archive.org"]

[prod]
SCHOLAR_ENV = "prod"
FATCAT_ELASTICSEARCH_BACKEND = "https://search.qa.fatcat.wiki"
ELASTICSEARCH_FULLTEXT_INDEX = "scholar_fulltext_v01"
ELASTICSEARCH_BACKEND = "http://localhost:9200"
KAFKA_BROKERS = ["wbgrp-svc263.us.archive.org"]
ENABLE_GOATCOUNTER = true
GOATCOUNTER_ENDPOINT = "/goatcounter/count"
GOATCOUNTER_SCRIPT_URL = "/goatcounter/count.js"
